const config = {
  WIDTH: 800,
  HEIGHT: 600,
  SCREEN_RATIO: 8 / 6,
  BACKGROUND_COLOR: 0x69f0f5,
  PRIMARY_COLOR: 0x0f4a02,
  GROUND_HEIGHT: 50,
  MAX_CHARACTER_VELOCITY: 6,
  CHARACTER_POWER: 10,
  CHARACTER_GRAVITY_Y: 1,
  FOOD_DROP_INTERVAL: 150,
  FOOD_INTERVAL_DECREASE_BY_SCORE_MULTIPLY: 0.2,
  MIN_FOOD_VELOCITY: 2,
  MAX_DEFAULT_FOOD_VELOCITY: 5,
  ADDITIONAL_FOOD_VEOLICTY_SCORE_MULTIPLY: 0.01,

  SCORE_PER_FOOD: 10,
  LIVES: 10
}

export default config
